# LAB 2 : Data Preprocessing Tools

## Import libraries

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Import dataset

In [14]:
dataset = pd.read_csv('onlinefoods.csv')

## EDA Steps(Exploratory Dataset Analysis)

In [15]:
dataset.head()

Educational Qualifications  Age  Monthly Income Output
0                   Graduate   22           25000    Yes
1                       Ph.D   25           50000    Yes
2              Post Graduate   22           25000    Yes
3              Post Graduate   25           25000    Yes
4              Post Graduate   27           25000    Yes

In [16]:
dataset.shape

(20, 4)

In [17]:
dataset.columns

Index(['Educational Qualifications', 'Age', 'Monthly Income', 'Output'], dtype='object')

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Educational Qualifications  20 non-null     object
 1   Age                         20 non-null     int64 
 2   Monthly Income              20 non-null     int64 
 3   Output                      20 non-null     object
dtypes: int64(2), object(2)
memory usage: 768.0+ bytes


In [19]:
# descriptive statastics for numerical features
dataset.describe()

Age  Monthly Income
count  20.000000       20.000000
mean   24.800000    35000.000000
std     2.307881    12565.617249
min    22.000000    25000.000000
25%    23.750000    25000.000000
50%    24.000000    25000.000000
75%    26.000000    50000.000000
max    31.000000    50000.000000

In [20]:
# descriptive statastics for categorical features
dataset.describe(include= 'object')

Educational Qualifications Output
count                          20     20
unique                          3      2
top                 Post Graduate    Yes
freq                           10     14

## Preprocessing Steps

### Step 1 : Divide dataframe into independent variable/input and dependent / output Featutres

In [21]:
X = dataset.iloc [ : , :-1 ]
Y = dataset.iloc [ : , -1]

In [22]:
print(X)

   Educational Qualifications  Age  Monthly Income
0                    Graduate   22           25000
1                        Ph.D   25           50000
2               Post Graduate   22           25000
3               Post Graduate   25           25000
4               Post Graduate   27           25000
5               Post Graduate   22           25000
6                        Ph.D   31           50000
7               Post Graduate   23           50000
8                    Graduate   24           25000
9                        Ph.D   24           50000
10              Post Graduate   24           25000
11              Post Graduate   24           50000
12              Post Graduate   24           25000
13                   Graduate   28           25000
14              Post Graduate   27           50000
15                       Ph.D   26           25000
16                   Graduate   26           50000
17              Post Graduate   24           25000
18                   Graduate  

In [23]:
print(Y)

0     Yes
1     Yes
2     Yes
3     Yes
4     Yes
5     Yes
6     Yes
7     Yes
8     Yes
9     Yes
10     No
11    Yes
12    Yes
13     No
14     No
15     No
16     No
17     No
18    Yes
19    Yes
Name: Output, dtype: object


### Step 2: Handle the missing values in Dataset

In [24]:
'''from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,
                       strategy = 'mean')
imputer.fit(X.iloc[:,1:3])
X.iloc[:,1:3] = imputer.transform(X.iloc[:,1:3])
print(X)'''

"from sklearn.impute import SimpleImputer\nimputer = SimpleImputer(missing_values = np.nan,\n                       strategy = 'mean')\nimputer.fit(X.iloc[:,1:3])\nX.iloc[:,1:3] = imputer.transform(X.iloc[:,1:3])\nprint(X)"

### Step 3 : Encoding categorical data

In [25]:
dataset['Educational Qualifications'].value_counts()

Post Graduate    10
Graduate          6
Ph.D              4
Name: Educational Qualifications, dtype: int64

In [26]:
dataset['Output'].value_counts()

Yes    14
No      6
Name: Output, dtype: int64

**A. Encoding the Independent Variable (i/p feature/X)**

In X we have Educational Qualifications as categorical feature

It has 3 categories

Hence used One hot encoder

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder',
                                     OneHotEncoder(),
                                     [0])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [28]:
print(X)

[[1.0e+00 0.0e+00 0.0e+00 2.2e+01 2.5e+04]
 [0.0e+00 1.0e+00 0.0e+00 2.5e+01 5.0e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.2e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.5e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.2e+01 2.5e+04]
 [0.0e+00 1.0e+00 0.0e+00 3.1e+01 5.0e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.3e+01 5.0e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.4e+01 2.5e+04]
 [0.0e+00 1.0e+00 0.0e+00 2.4e+01 5.0e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.4e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.4e+01 5.0e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.4e+01 2.5e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.8e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 5.0e+04]
 [0.0e+00 1.0e+00 0.0e+00 2.6e+01 2.5e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.6e+01 5.0e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.4e+01 2.5e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.2e+01 2.5e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.6e+01 5.0e+04]]


**B. Encoding the Dependent Variable (o/p feature/ target / Y)**

Here there only two categories in Y i.e. Yes/No

Hence used Label encoder

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

Y = le.fit_transform(Y)

In [30]:
print(Y)

[1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1]


### Step 4 : Splitting Data into Training and Testing

In [31]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                        test_size = 0.3,
                                    random_state =1)

In [32]:
print(X_train)

[[0.0e+00 0.0e+00 1.0e+00 2.7e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.4e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.3e+01 5.0e+04]
 [0.0e+00 1.0e+00 0.0e+00 2.5e+01 5.0e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.8e+01 2.5e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.2e+01 2.5e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.6e+01 5.0e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.2e+01 2.5e+04]
 [0.0e+00 1.0e+00 0.0e+00 2.4e+01 5.0e+04]
 [0.0e+00 1.0e+00 0.0e+00 2.6e+01 2.5e+04]
 [1.0e+00 0.0e+00 0.0e+00 2.4e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.4e+01 2.5e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.4e+01 5.0e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.2e+01 2.5e+04]]


### Step 5 : Feature Scaling

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])

In [34]:
print(X_test)

[[ 0.          0.          1.         -0.29827499 -1.        ]
 [ 1.          0.          0.          0.059655    1.        ]
 [ 0.          1.          0.          1.84930496  1.        ]
 [ 0.          0.          1.         -0.65620498 -1.        ]
 [ 0.          0.          1.         -1.37206497 -1.        ]
 [ 0.          0.          1.          0.41758499  1.        ]]


### Q1. When to use label Encoder and when to use OneHotEncoder
#### Ans: LabelEncoder is used when dealing with categorical variables that exhibit an inherent ordinal relationship, and OneHotEncoder is used for nominal categorical variables where there is no meaningful order among the categories.
#### When dealing with categorical variables with more than two categories, it's often preferable to use OneHotEncoder to ensure that the model treats each category as a distinct entity without implying any ordinality. This approach helps maintain the integrity of the categorical data and prevents the model from making incorrect assumptions about the relationships among the categories.

### Q2. Write a code to Feature Scaling our dataset numerical variable using MinMaxScaler

In [35]:
from sklearn.preprocessing import MinMaxScaler
s = MinMaxScaler ()
X_train[:,3:] = s.fit_transform(X_train[:,3:])
X_test[:,3:] = s.fit_transform(X_test[:,3:])
print(X_test)

[[0.         0.         1.         0.33333333 0.        ]
 [1.         0.         0.         0.44444444 1.        ]
 [0.         1.         0.         1.         1.        ]
 [0.         0.         1.         0.22222222 0.        ]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         1.         0.55555556 1.        ]]


### Q3. For below student dataset remove missing values from column 'gender' & 'Marks'

In [36]:
students=[[85,'M','verygood'],[95,'F','excellent'],
          [75,None,'good'],[np.NaN,'M','average'],
          [70,'M','good'],[np.NaN,None,'verygood'],
          [92,'F','verygood'],[98,'M','excellent']]
dfstd=pd.DataFrame(students)
dfstd.columns=['marks','gender','result']
#Removing rows with missing values in 'gender' and 'marks' columns
dfstd.dropna(subset=['gender','marks'],inplace=True)
print(dfstd)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
4   70.0      M       good
6   92.0      F   verygood
7   98.0      M  excellent


### 

### Q4. For dataset given above apply proper Categorical Encoder to encode column 'gender' and 'result'

In [37]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
dfstd['gender_encoded']=l.fit_transform(dfstd['gender'].astype(str))
dfstd['result_encoded']=l.fit_transform(dfstd['result'].astype(str))
print(dfstd)

   marks gender     result  gender_encoded  result_encoded
0   85.0      M   verygood               1               2
1   95.0      F  excellent               0               0
4   70.0      M       good               1               1
6   92.0      F   verygood               0               2
7   98.0      M  excellent               1               0
